### ISSUE TITLE
Convergence in time diagnostic

### ISSUE THREAD

**Issue by mrhardman** [mabarnes/moment_kinetics#106]
The current post_processing.jl script does not provide a global test of the convergence of the simulations in time. The best option is to look at the heatmaps of z or r vs t, but these do not neatly capture the entire solution. It may be useful to introduce a plot of the volume-averaged moments with time as a way of quickly determining if the simulation is close to steady state.

**Comment by johnomotani** [comment]
We could also compute something like the RMS of the difference between consecutive time points and plot that - would be a stricter test?

**Comment by mrhardman** [comment]
That sounds like a good idea. I think we might need both plots. I would guess that we would want to know the RMS d f / d t divided by the RMS f to get an idea for how much the changes are affecting the total solution. For a plasma at very low density, a small d f / d t could be significant.
