### ISSUE TITLE
--package option not recognised when trying to run using new README.md instructions

### ISSUE THREAD

**Issue by mabarnes** [mabarnes/moment_kinetics#11]
I have tried running moment_kinetics with the latest version of the source using the command
> julia -O3 --package -Jdependencies.so run_moment_kinetics.jl
as indicated in the README.md file.  When I do so I get the error message
> ERROR: unknown option `--package`

Not sure if there is something else I am meant to do (other than creating dependencies.so) before using the above command or if there is some other problem.

**Comment by mabarnes** [comment]
Is it possible that the --package flag should instead be --project?  This seems to work for me.

**Comment by johnomotani** [comment]
> Is it possible that the --package flag should instead be --project? This seems to work for me.

Yes, it should have been. I don't know why, but my fingers always want to type `--package` instead, even though it's never been a valid option for anything!

**Comment by johnomotani** [comment]
...I'll fix the readme.
