### ISSUE TITLE
Swap order of z and vpa dimensions?

### ISSUE THREAD

**Issue by johnomotani** [mabarnes/moment_kinetics#21]
Was there a reason for choosing to make the z dimension the fastest-changing index ('inner' dimension) in the distribution function arrays, rather than vpa? I the places I'm looking at the moment, because we have to integrate over vpa and do operations like normalise `f[iz,:,is]` by `density[iz,is]`, etc., it looks like it would be more efficient to have vpa as the fastest-changing index (contiguous in memory).

I'm currently doing some profiling and trying to fix the extra allocations that julia does if you're not very careful, and I think in some places this would be simplified (as well as more efficient) by swapping z and vpa dimensions.

@mabarnes unless there are reasons why this is a bad idea, I'll have a go at implementing, and I'll take responsibility for fixing any merge conflicts with stuff you've been working on...

**Comment by JosephThomasParker** [comment]
It would be interesting to hear what Michael has to say, but I think you're right. The big scaling bottlenecks will come from integrals over v in the field solve and in collision operators, while z should be halo-swap finite differences.

**Comment by mabarnes** [comment]
I agree with you, John.  I think the ordering of the indices is more historical, in the sense that I first did a 1d code in z and then added vpa on.  I don't see a good reason not to swap the indices now.
