### ISSUE TITLE
Markdown docs not rendering correctly

### ISSUE THREAD

**Issue by mrhardman** [mabarnes/moment_kinetics#229]
I am currently adding some documentation. Looking for syntax inspiration in existing docs, e.g., https://github.com/mabarnes/moment_kinetics/blob/master/docs/src/moment_kinetic_equations.md, I note that the equations there are not rendering correctly. LaTeX should be a fairly static language -- has markdown changed since these docs were first compiled?

**Comment by johnomotani** [comment]
The docs are not written in 'pure' Markdown, they're designed to be processed by Documenter.jl into html (or pdf). The rendered docs display correctly: https://mabarnes.github.io/moment_kinetics/dev/moment_kinetic_equations/.
