### ISSUE TITLE
Refactor namelist inputs for coordinates and other inputs

### ISSUE THREAD

**Issue by mrhardman** [mabarnes/moment_kinetics#241]
Should we prioritise refactoring the coordinate, evolve_moments, drive, and remaining collisions inputs to use a namelist format?

This may have the benefit of reducing clutter in `moment_kinetics_input.jl`, as well an making the specification of the defaults unique. 

Is there any reason for why we should not refactor the input structure for these inputs?

@johnomotani @LucasMontoya4

**Comment by mrhardman** [comment]
@johnomotani Comments on https://github.com/mabarnes/moment_kinetics/pull/181#issuecomment-2334100381.

The structure below is how we might hope to set the coordinate data.
```
foo_input = OptionsDict("foo" => OptionsDict("ngrid" => 5, "nelement" => 10))
define_coordinate(foo_input, "foo")
```
However, there are some complications that I will note in case it is helpful. At the moment we have an intermediate input_struct for coordinate data that we fill from .toml data in `moment_kinetics_input.jl`. Once we fill this mutable struct, we set up the MPI with this information and then we pass that data into another input_struct which is then passed to `define_coordinate()`.

When making other refactors from flat .toml to namelists, I endevoured to use @johnomotani's method of using `set_defaults_and_check_section!()` to make an `OptionsDict`, where conditional values to the options are set in default appropriately, or in the function immediately following the namelist read (e.g. in https://github.com/mabarnes/moment_kinetics/blob/db370d14451aff4ab167e823fb774229923d0c8b/moment_kinetics/src/species_input.jl#L16). Then this dictionary is passed into the pre-defined input struct, e.g., as in https://github.com/mabarnes/moment_kinetics/blob/db370d14451aff4ab167e823fb774229923d0c8b/moment_kinetics/src/species_input.jl#L197. This method has the nice benefit of a definitely typed struct as a result of the input data read, and a single location to determine the default values in the struct. It would be good to use this method of setting a struct once and forever throughout the code, if possible, so that reading input data looks somewhat standard for all features. It would be possible to avoid using a struct for output of the input data function (like with the timestepping options, where I think a Dict is passed around, rather than a struct), but then the input data can be changed at run-time elsewhere in the code with potential unexpected consequences.

My comment for reading the coordinate data is therefore that we might want to write the function to read coordinate data to the intermediate (but not mutable) struct `grid_input` https://github.com/mabarnes/moment_kinetics/blob/db370d14451aff4ab167e823fb774229923d0c8b/moment_kinetics/src/input_structs.jl#L216, to permit setting of the MPI communicators within the setup function, before passing the `grid_input` struct around the code as is done at present.

**Comment by johnomotani** [comment]
Yeah, I ran into this - got around it by making a function that reads the options and puts them in a NamedTuple. That function can be called inside `define_coordinate()` or before, and then it's output passed into `define_coordinate()`.

**Comment by mrhardman** [comment]
So I guess that your function creates a NamedTuple with the MPI communicator by default to be NULL, but otherwise sets up to the MPI using the existing functions? Does that mean that you have to create all the coordinate NameTuples at once?

Is function general enough that you can create coordinates with names that don't already exist in the moment kinetics source? (like here https://github.com/mabarnes/moment_kinetics/blob/aad7e274a2645577c1120eae6e622aecd3ed489c/moment_kinetics/test/poisson_radial_polar_tests.jl#L97).
