### ISSUE TITLE
Boltzmann electron simulation plotting electron physics

### ISSUE THREAD

**Issue by LucasMontoya4** [mabarnes/moment_kinetics#252]
If I run a Boltzmann simulation with the new inputs (which means adding nothing to the composition section), there are no loops suggesting that kinetic electrons are being run (as you'd expect!). However, using makie_post_processing outputs plots for electrons as well. They are given all of the moments plotted, and the density is of course matching the ion one, but the heat flux and flow are zero, suggesting this is still a Boltzmann response simulation. The temperature, though, is not constant, which leads me to believe that the ion parameters are being plotted under the title of electrons? Please let me know if anyone can reproduce this, as it only started after I fetched the master today.

**Comment by johnomotani** [comment]
I don't think this caused a big problem, because I don't think `electron_vth` or `electron_temp` were used in simulations using Boltzmann response, but they were initialised to incorrectly (equal to the ion temperature, rather than a constant `T_e`). I'll make a PR to fix them, just in case.

**Comment by LucasMontoya4** [comment]
Thank you!
