### ISSUE TITLE
sphinx documentation?

### ISSUE THREAD

**Issue by johnomotani** [mabarnes/moment_kinetics#29]
`README.md` is getting a bit long now. It might be nice to set up better documentation. I've used [sphinx](https://www.sphinx-doc.org) plus [readthedocs.io](https://readthedocs.io) before to generate online docs, and I think they work with Julia. Anyone have other preferences?

**Comment by mabarnes** [comment]
I also have no strong opinion; would be useful to have some documentation setup, so happy to go with your suggestion

**Comment by johnomotani** [comment]
Unfortunately the project providing julia support for sphinx (https://github.com/bastikr/sphinx-julia) seems to be not active any more, although some people who are still using it added a bug-fix last year. sphinx-julia is not working for me with the latest version of sphinx.

The other option I've found is Documenter.jl (https://github.com/JuliaDocs/Documenter.jl), which is what julia uses to build its own documentation (so pretty sure it will keep being actively developed!).

Documenter.jl seems a bit bare-bones. For example, it does not automatically show the arguments of a method (I guess the reason is that Julia expects you to document the top-level 'function' `foo()`, while all the particular 'methods' `foo(i::Int)`, etc., may have different arguments and argument types). I'd hoped the sphinx version might give us some of the fancier features like it has for Python documentation, but even if we could get it working now, it seems likely to break again, so not worth pursuing further.

I'm putting together a branch with Documenter.jl docs. Seems not too complicated so far...
