### ISSUE TITLE
error downloading/installing dependencies after PR 39

### ISSUE THREAD

**Issue by mabarnes** [mabarnes/moment_kinetics#40]
Just pulled the latest Master (post-PR39 merge) and tried `pkg> instantiate`, but got the error message "ERROR: TypeError: in typeassert, expected VersionNumber, got a value of type Pkg.Types.VersionSpec".  The stack trace for the error does not look very helpful to me, with pointers to Julia's own files.  I do not receive this error if running instantiate with the pre-PR39 version of Master.

**Comment by johnomotani** [comment]
What Julia version are you using? I've updated to 1.7.0, seems possible that something broke backward compatibility...

**Comment by johnomotani** [comment]
I get the same error if I try to use julia-1.6.3.

Sorry, didn't realise I'd made a change that would do that!

**Comment by mabarnes** [comment]
I'm still using 1.6.2.  Is the solution to require Julia > 1.7, or do you think there is a simple fix?

**Comment by johnomotani** [comment]
I don't know if there's a fix for julia-1.6 - I don't understand what the actual issue is! Requiring julia>=1.7 seems like the simplest answer.

**Comment by mabarnes** [comment]
I'll give it a go.

**Comment by mabarnes** [comment]
updating to v1.7.1 fixed the error for me as well.  I'll close this issue, and we should just be sure to update the README to reflect the requirement that v > 1.7 is required.
