### ISSUE TITLE
Broken tests in master

### ISSUE THREAD

**Issue by mrhardman** [mabarnes/moment_kinetics#47]
Some of the tests provided in master return as broken. What does this indicate? 

Looking at the current master branch (using git log) 

commit 74e16e935304ade85fcd46c2071c0185864ab5d4 (HEAD -> master, origin/master, origin/HEAD)

we can run the tests via the REPL, to find

> using moment_kinetics
> include("test/runtests.jl")
calculus tests
interpolation tests
sound wave tests
    - testing finite_difference
    - testing finite_difference_split_3_moments
    - testing chebyshev_pseudospectral
    - testing chebyshev_pseudospectral_split_1_moment
    - testing chebyshev_pseudospectral_split_2_moments
    - testing chebyshev_pseudospectral_split_3_moments
nonlinear sound wave tests
    - testing finite_difference
    - testing finite_difference_split_1_moment
    - testing chebyshev_pseudospectral
    - testing chebyshev_pseudospectral_split_1_moment
Harrison-Thompson wall boundary condition tests
    - testing chebyshev_pseudospectral
Wall boundary condition tests
    - testing chebyshev_pseudospectral
Test Summary:         |  Pass  Broken  Total
moment_kinetics tests | 29496       6  29502

Note the 6 broken tests.

**Comment by johnomotani** [comment]
'Broken' really means 'expected fail'. Not the best terminology, but it's what the `Base.Test` module uses for 'known-broken' tests, or tests that have to be skipped for any other reason. The reason for skipping the tests should be printed in the test summary, but you might need to pass `--verbose` (or `-v`) when running the tests to see it.
