### ISSUE TITLE
Create docs page

### ISSUE THREAD

**Issue by johnomotani** [mabarnes/moment_kinetics#55]
@mabarnes could you please create a 'Github pages' page pointing to the `gh-pages` branch?

Super quick how-to:
* go to Settings->Pages
* Set the 'Source' to `gh-pages` from the drop-down menu
* Pick any theme - doesn't matter which because whatever the theme does is overridden by `Documenter.jl` anyway
* Click save

Then our docs should get published to https://mabarnes.github.io/moment_kinetics/ :smiley:

**Comment by mabarnes** [comment]
I think I have finally done this -- please let me know if it's what you were expecting!

**Comment by johnomotani** [comment]
Looks good :smiley: :tada:
