### ISSUE TITLE
All MPI controlled processes do not exit with error on a single process

### ISSUE THREAD

**Issue by mrhardman** [mabarnes/moment_kinetics#65]
When running with MPI, I have noticed that if there is an error that causes Julia to abort the calculation on a single process, then the program does not exit all processes. Instead, the MPI processes which have not met an error remain stalled. This may be dependent on the architectural which we run the code.

**Comment by johnomotani** [comment]
Yes, I've noticed the same problem. I've attempted a solution on my 1D1V branch in 7cac085cbe12bc7f3951588fad32622de89f7f43 and 7efef078c5ff86d567ea328cf10aa79209703650. Not sure it works all the time though...

**Comment by mrhardman** [comment]
Potentially related to https://github.com/mabarnes/moment_kinetics/issues/86. Closing as stale, can re-open if similar issues are reported.
