### ISSUE TITLE
NCDataset incompatibility 

### ISSUE THREAD

**Issue by mrhardman** [mabarnes/moment_kinetics#66]
After leaving the source code for a period, I have rebuilt from scratch the branch radial-vperp-standard-DKE-with-neutrals on commit 19ba012d11c5a0fb2c55d45547fa070ec27f30e7 , using Julia/1.7.2

I have found an issue where I am unable to run the code if I build a new Manifest.toml, whereas if I use the old Manifest that is contained within the repo, the code runs fine without complaint. 

$ git clone https://github.com/mabarnes/moment_kinetics.git moment_kinetics
$ cd moment_kinetics/; git checkout radial-vperp-standard-DKE-with-neutrals
$ mv Manifest.toml Manifest_old.toml
$ julia --project

(moment_kinetics) pkg> instantiate

julia> using Pkg

julia> Pkg.test(; test_args=["--long"])

Leads to the following error

 Got exception outside of a @test
  MethodError: Cannot `convert` an object of type
    NCDatasets.CFVariable{Float64, 1, NCDatasets.Variable{Float64, 1, NCDatasets.NCDataset{Nothing}}, NCDatasets.Attributes{NCDatasets.NCDataset{Nothing}}, NamedTuple{(:fillvalue, :missing_values, :scale_factor, :add_offset, :calendar, :time_origin, :time_factor), Tuple{Nothing, Tuple{}, Nothing, Nothing, Nothing, Nothing, Nothing}}} to an object of type
    Union{NCDatasets.CFVariable{Float64, 1, NCDatasets.Variable{Float64, 1, NCDatasets.NCDataset}, NCDatasets.Attributes{NCDatasets.NCDataset{Nothing}}, NamedTuple{(:fillvalue, :scale_factor, :add_offset, :calendar, :time_origin, :time_factor), NTuple{6, Nothing}}}, NCDatasets.CFVariable{Float64, 1, NCDatasets.Variable{Float64, 1, NCDatasets.NCDataset{Nothing}}, NCDatasets.Attributes{NCDatasets.NCDataset{Nothing}}, NamedTuple{(:fillvalue, :scale_factor, :add_offset, :calendar, :time_origin, :time_factor), NTuple{6, Nothing}}}}

**Comment by mrhardman** [comment]
Both old (in repo) and 'new' (generated on the fly) Manifests claim to use 

NetCDF version: 4.7.4 of Jan 26 2021 22:46:58

However, the Pkg.test("NCDatasets") report differs depending on which manifest is used. For the 'old' case

NetCDF library: /home/h/hardman/.julia/artifacts/0a7f440ba143b238cc3dd0def2956d34d76755f3/lib/libnetcdf.so
NetCDF version: 4.7.4 of Jan 26 2021 22:46:58 $
Test Summary: | Pass  Broken  Total
NCDatasets    |  733      10    743
Test Summary:  | Pass  Total
NetCDF4 groups |    9      9
Test Summary:          | Pass  Total
Variable-length arrays |   22     22
Test Summary:      |   Pass   Total
Time and calendars | 874621  874621
Test Summary:       | Pass  Total
Multi-file datasets |   60     60
Test Summary:     | Pass  Total
Deferred datasets |   13     13
     Testing NCDatasets tests passed


whereas for the 'new' case 

NetCDF library: /home/h/hardman/.julia/artifacts/0a7f440ba143b238cc3dd0def2956d34d76755f3/lib/libnetcdf.so
NetCDF version: 4.7.4 of Jan 26 2021 22:46:58 $
Test Summary: | Pass  Total
NCDatasets    |  829    829
Test Summary:  | Pass  Total
NetCDF4 groups |    9      9
Test Summary:          | Pass  Total
Variable-length arrays |   22     22
Test Summary:  | Pass  Total
Compound types |   16     16
Test Summary:      | Pass  Total
Time and calendars |   23     23
Test Summary:       | Pass  Total
Multi-file datasets |   70     70
Test Summary:     | Pass  Total
Deferred datasets |   13     13
Test Summary: | Pass  Total
@select macro |   33     33
     Testing NCDatasets tests passed

In the 'old' case, some tests were broken, whereas in the new case, all tests pass, and there are more of them!

**Comment by mrhardman** [comment]
I should note that these tests were performed all using Julia/1.7.2

**Comment by johnomotani** [comment]
Oh, sorry this error I know! When the julia wrapper (NCDatasets.jl) updated, its internal types changed slightly. If you cherry-pick ab2c04c6dfb0c3de40449a1e40c08aee03757c54 that should fix it, and prevent this problem from happening again. That commit changes the `netcdf_info` struct so it uses some generic parameters for the concrete types of the `CFVariable` variables.

**Comment by johnomotani** [comment]
I don't know. I got the same error. The next thing I'd try is to delete (or maybe better just move) my `~/.julia` go get rid of all the existing packages and try a clean install. Although, it looks like the same error as on the CI server, which should be starting from a clean state, so maybe won't help. ~~Could just be that NCDatasets.jl is somehow messed up~~ this looks like a known issue https://github.com/Alexander-Barth/NCDatasets.jl/issues/182 which there is some plan to fix in the near future.

We could just wait for a fix, or we could temporarily pin Julia in the CI to 1.7.2. Pinning the version should be as simple as changing, in the `.github/workflows/*.yml` files
```
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1'
          arch: x64
```
to
```
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1.7.2'
          arch: x64
```
I think, although I haven't tested this....

**Comment by mrhardman** [comment]
Making a fresh installation we have 

$ git clone https://github.com/mabarnes/moment_kinetics.git moment_kinetics_test
$ cd moment_kinetics_test
$ module load julia/1.8.0
$ module load intel-compilers openmpi/4.0.1-intel
$ rm Manifest.toml
$ julia --project

(moment_kinetics) pkg> instantiate

(moment_kinetics) pkg> status --outdated -m
Project moment_kinetics v0.1.0
Status `~/excalibur/moment_kinetics_test/Manifest.toml`
⌅ [ffbed154] DocStringExtensions v0.8.6 (<v0.9.1): MPI
⌅ [05181044] RelocatableFolders v0.1.3 (<v0.3.0): PackageCompiler
⌅ [0234f1f7] HDF5_jll v1.12.0+1 (<v1.12.2+1): NetCDF_jll
⌅ [7243133f] NetCDF_jll v400.702.400+0 (<v400.802.103+0): NCDatasets

julia> using Pkg

julia> Pkg.test(; test_args=["--long"])

Precompiling project...
  ✗ NCDatasets
  ✗ moment_kinetics
  29 dependencies successfully precompiled in 72 seconds. 170 already precompiled.
  2 dependencies errored. To see a full report either run `import Pkg; Pkg.precompile()` or load the packages
     Testing Running tests...
ERROR: LoadError: InitError: could not load library "/home/h/hardman/.julia/artifacts/0a7f440ba143b238cc3dd0def2956d34d76755f3/lib/libnetcdf.so"
libmbedtls.so.13: cannot open shared object file: No such file or directory

**Comment by mrhardman** [comment]
I would be keen to pin to Julia/1.7.2 whilst we wait for the Julia/1.8.0-compatible NCDatasets to come online. This project's great strength is the testing capability, so if we present the git repository when all tests are failing, it does not look very good on the developers at all.

**Comment by johnomotani** [comment]
@mrhardman :+1: sounds good to me. We can just leave an issue open to remind us to check in future for when we can un-pin again.

**Comment by mrhardman** [comment]
@johnomotani 

I don't appear to have the right privileges to push these changes, even in a branch:

$ git push
Counting objects: 10, done.
Delta compression using up to 40 threads.
Compressing objects: 100% (9/9), done.
Writing objects: 100% (10/10), 963 bytes | 481.00 KiB/s, done.
Total 10 (delta 7), reused 0 (delta 0)
remote: Resolving deltas: 100% (7/7), completed with 7 local objects.
To https://github.com/mabarnes/moment_kinetics.git
 ! [remote rejected] radial-vperp-standard-DKE-with-neutrals -> radial-vperp-standard-DKE-with-neutrals (refusing to allow a Personal Access Token to create or update workflow `.github/workflows/debug_checks.yml` without `workflow` scope)
error: failed to push some refs to 'https://github.com/mabarnes/moment_kinetics.git'

**Comment by johnomotani** [comment]
That's surprising - I don't think I have admin rights or anything and I've changed these! I'll have a try now...

**Comment by mrhardman** [comment]
The cause is here https://github.com/orgs/community/discussions/26254

**Comment by mrhardman** [comment]
With how-to info here https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token

**Comment by mrhardman** [comment]
I have just pushed the changes, let's hope we have the solution.

**Comment by mrhardman** [comment]
@johnomotani  

In fact, I did break something:

https://github.com/mabarnes/moment_kinetics/actions/runs/2883228403

**Comment by johnomotani** [comment]
Apparently there's a 'partial outage' on Github actions at the moment https://www.githubstatus.com/
So the problem may be nothing to do with us...

**Comment by mrhardman** [comment]
I wondered if Github would allow us to specify Julia 1.7.2 ? It looks from here 

https://github.com/julia-actions/setup-julia#julia-versions

and here

https://julialang-s3.julialang.org/bin/versions.json

that version = '1.7.2' should be a sensible thing to specify

**Comment by johnomotani** [comment]
The more I look at it, the more it seems likely it's a Github problem. It looks like the Action is failing to even start up it's runner. If we'd caused the problem, it would show up in step 1 or 2 of the workflow, and then we should get some actual log files, not the weird errors like the one you linked to. Github say they're
>Investigating - We are investigating reports of degraded performance for Actions.
Aug 18, 14:33 UTC

which is only 1/2 an hour ago, so hopefully they'll fix that soon and we can try again...

**Comment by mrhardman** [comment]
It seems that the tests for https://github.com/mabarnes/moment_kinetics/commit/8b7f18d965a37980198eb900ca7b8c61addc7aa3 now pass apart from 

https://github.com/mabarnes/moment_kinetics/runs/7902593328?check_suite_focus=true

Which was known to fail in previous versions (I think because of the way the MPI was set up, although @johnomotani is the expert on this point).

**Comment by johnomotani** [comment]
:tada: nice! I tried restarting them during the JPP seminar. Github must have fixed their servers enough :-)

I did expect those debug checks to fail as they probably need to run on 16 or maybe 32 processes. The error on that job looks strange though, it's not the kind I was expecting. I'll try and have a look at it soon...

**Comment by johnomotani** [comment]
The problems with `NCDatasets.jl` seem to be fixed now - I've just tested with julia-1.8.0 (deleting and re-generating the Manifest.toml) and the tests pass.

Using julia-1.8.0 will require updating the Maniest.toml. At least for NCDatasets.jl I think that update won't be backward-compatible to julia-1.7.x. I'm happy to make the change any time, but not in any rush. When we do we can un-pin the julia version in the CI tests. Do we want to upgrade to julia-1.8.0?

**Comment by mrhardman** [comment]
That is good news! Unless you are sure that the changes required to upgrade are trivial, I think it would be good to hold off the upgrade until mid-September in case attendees of the Neptune Workshop wish to try running/testing the code. What is your opinion?

**Comment by mabarnes** [comment]
I'm happy to go ahead with the upgrade.  I personally had to upgrade to Julia 1.8+ anyway recently in order to overcome the issues I was having getting the code to run on my laptop.

**Comment by johnomotani** [comment]
Sounds good to me, let's go for 1.8.x then!

**Comment by johnomotani** [comment]
... in upgrading it looks like the way to set up MPI.jl if you want to use system MPI rather than the julia-provided one has changed, see https://juliaparallel.org/MPI.jl/stable/configuration/#configure_system_binary for the new version.

**Comment by johnomotani** [comment]
I think all the issues in this thread are resolved now.
